### ISSUE TITLE
Looks like code is not working 

### ISSUE THREAD

**Issue by basav22** [zackify/stock-api#1]
Hello,

My Linux setup 
**Node: v12.19.0**

I get this error - 
```stock-api git:(master) ✗ npm start

> stockapi@1.0.0 start /home/basavaraj/repos/personal/share-bazzar/stock-api
> node stockapi.js

/home/basavaraj/repos/personal/share-bazzar/stock-api/stockapi.js:17
    () => document.querySelector("g-card-section > span")?.textContent
                                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by zackify** [comment]
Node v12 doesn’t support the ?. Operator. 

Update to 14 and up for it to work :)

also there’s no guarantee that it works anymore, google can change their site markup at anytime.
